version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
      - "8081:8081"  # Expose API port
    volumes:
      - ./articles:/root/articles
    environment:
      - GITHUB_USERNAME=kubeden
      - GITHUB_REPO=kubeden
      - README_FILE=README.md
      - INFO_FILE=INFO.md
      - X_USER_FULL_NAME=Kuberdenis
      - X_USERNAME=kubeden
      - TEMPLATE_CHOICE=ssi

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app