version: '3'
services:
  blog:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/articles:/app/articles
      - ${PWD}/templates:/app/templates
      - ${PWD}/static:/app/static
    environment:
      - GIN_MODE=debug