version: '3'

services:
  app:
    build: .
    ports:
      - "8080"
    volumes:
      - ./articles:/root/articles

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app